- name: "Создание директории для данных docker"
  ansible.builtin.file:
    path: "{{docker_data}}"
    state: directory
    force: no

- name: "Конфигурирование Haproxy Debian"
  include_tasks: "debian.yml"
  when: ansible_os_family == "Debian"

- name: "Конфигурирование Haproxy CentOS"
  include_tasks: "centos.yml"
  when: ansible_os_family == "RedHat"

- name: "Сборка контейнера из docker-compose файла"
  ansible.builtin.command: "docker compose -f {{docker_data}}/docker-compose.yml up -d"
  register: compose_result
  ignore_errors: yes

- name: "Проверка успешности запуска контейнеров"
  ansible.builtin.debug:
    msg: "Контейнеры успешно запущены"
  when: compose_result.rc == 0

- name: "Обработка ошибки запуска контейнеров"
  ansible.builtin.fail:
    msg: "Не удалось запустить контейнеры"
  when: compose_result.rc != 0
