- name: "Установка Zabbix Agent 2 на Debian"
  include_tasks: "debian.yml"
  when: ansible_os_family == "Debian"

- name: "Установка Zabbix Agent 2 на CentOS"
  include_tasks: "centos.yml"
  when: ansible_os_family == "RedHat"
