version: '3.8'

services:

  admin_helper:
    container_name: admin_helper
    build: ./images/admin_helper
    image: admin_helper:1.0
    #volumes:
    #  - ./ansible:/ansible
    #ports:
    #  - 8000:8000
    networks:
      - backend

  web:
    image: nginx:latest
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
      - ./web/www:/var/www/html
    depends_on:
      - admin_helper
    networks:
      - backend

networks:
  backend:
    driver: bridge