version: '3.8'

services:

  ansible:
    container_name: admin_helper
    build: ./images/ansible
    image: ansible
    volumes:
      - ./ansible:/ansible

  web:
    image: nginx:latest
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./web/conf.d:/etc/nginx/conf.d
      - ./web/www:/var/www/html