version: '3.8'
services:

  admin_helper:
    container_name: admin_helper
    build: ./images/admin_helper
    image: somekind/admin_helper_api:1.0.2
    volumes:
      - ./images/admin_helper/resources/ansible:/ansible
      - ./images/admin_helper/resources/api:/app
    networks:
      - backend
    ports:
      - 8000:8000

  admin_helper_web:
    build: ./images/web
    image: somekind/admin_helper_web:1.0.2
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./images/web/resources/conf.d:/etc/nginx/conf.d
      - ./images/web/resources/www:/var/www/html
    depends_on:
      - admin_helper
    networks:
      - backend

networks:
  backend:
    driver: bridge