version: '3.8'
services:
  admin_helper:
    container_name: AH_api
    image: somekind/admin_helper_api:1.0.0
    volumes:
      - ./admin_helper/ansible:/ansible
      - ./admin_helper/api:/app
    networks:
      - backend

  admin_helper_web:
    container_name: AH_web
    image: somekind/admin_helper_web:1.0.1
    ports:
      - 80:80
    volumes:
      - ./admin_helper/web/conf.d:/etc/nginx/conf.d
      - ./admin_helper/web/www:/var/www/html
    depends_on:
      - admin_helper
    networks:
      - backend

networks:
  backend:
    driver: bridge