version: '3.8'

services:

  admin_helper:
    container_name: admin_helper
    build: ./images/admin_helper
    image: somekind/admin_helper_api:1.0.0
    volumes:
      - ./images/admin_helper/dev/ansible:/ansible
      - ./images/admin_helper/dev/api:/app
    networks:
      - backend

  admin_helper_web:
    build: ./images/web
    image: somekind/admin_helper_web:1.0.1
    container_name: web
    ports:
      - 80:80
    volumes:
      - ./images/web/dev/conf.d:/etc/nginx/conf.d
      - ./images/web/dev/www:/var/www/html
    depends_on:
      - admin_helper
    networks:
      - backend

networks:
  backend:
    driver: bridge