- name: "Установка репозитория epel-release"
  ansible.builtin.yum_repository:
    name: epel
    description: Extra Packages for Enterprise Linux 7 - $basearch
    baseurl: https://download.fedoraproject.org/pub/epel/7/$basearch
    gpgcheck: yes
    gpgkey: https://download.fedoraproject.org/pub/epel/RPM-GPG-KEY-EPEL-7
    enabled: yes

- name: "Установка Prometheus Node Exporter"
  ansible.builtin.yum:
    name: golang-github-prometheus-node-exporter
    state: latest
    update_cache: yes

- name: "Редактирование конфига Node Exporter"
  ansible.builtin.copy:
    src: "node_exporter"
    dest: "/etc/sysconfig/node_exporter"

- name: "Перезапуск демона Node Exporter"
  ansible.builtin.service:
    name: node_exporter
    enabled: yes
    state: restarted
