##### Разворачивание HaProxy на хосте
---
- name: "Разворачивание HaProxy на хосте"
  #strategy: free
  #serial: "80%"
  hosts: haproxy_on_host
  become: true
  gather_facts: true
  gather_subset: all

  # переменные
  vars:
    # Сервера для балансировки
    balance_hosts:
      - "server_1 10.10.10.1"
      - "server_2 10.10.10.2"
    # Балансируемый порт (на фронтенде и на серверах)
    balance_port: 80
    # Название фронтенда
    frontend_name: "front_web-server"
    # Название бэкенда
    backend_name: "back_web-server"

  roles:
    - haproxy