- name: "Установка пакета yum-utils (если не установлен)"
  ansible.builtin.yum:
    name: yum-utils
    state: present

- name: "Добавление репозитория CentOS SCL"
  ansible.builtin.yum_repository:
    name: centos-sclo-rh
    description: CentOS SCL Repository
    baseurl: http://mirror.centos.org/centos/7/sclo/$basearch/rh/
    gpgcheck: yes
    gpgkey: https://www.centos.org/keys/RPM-GPG-KEY-CentOS-SIG-SCLo
    enabled: yes

- name: "Установка Haproxy 1.8"
  ansible.builtin.yum:
    name: rh-haproxy18-haproxy
    update_cache: yes
    state: latest

- name: "Установка зависимостей"
  ansible.builtin.yum:
    name: rh-haproxy18-haproxy-syspaths
    update_cache: yes
    state: latest

- name: "Проверка наличия бэкапа конфига"
  ansible.builtin.stat:
    path: "/etc/opt/rh/rh-haproxy18/haproxy/haproxy.cfg.backup"
  register: backup_file

- name: "Бэкап конфига Haproxy"
  ansible.builtin.file:
    src: "/etc/opt/rh/rh-haproxy18/haproxy/haproxy.cfg"
    dest: "/etc/opt/rh/rh-haproxy18/haproxy/haproxy.cfg.backup"
    state: hard
  when: not backup_file.stat.exists

- name: "Формирование конфига Haproxy"
  ansible.builtin.template:
    src: "haproxy.cfg.centos.j2"
    dest: "/etc/opt/rh/rh-haproxy18/haproxy/haproxy.cfg"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "o=rw,g=r,a=r"
  register: haproxy_config_result
#  vars:
#    pidfile: "/var/run/rh-haproxy18-haproxy.pid"

- name: "Создание директории /etc/haproxy"
  ansible.builtin.file:
    path: "/etc/haproxy"
    state: directory

- name: "Ссылка конфига Haproxy в /etc/haproxy"
  ansible.builtin.file:
    src: "/etc/opt/rh/rh-haproxy18/haproxy/haproxy.cfg"
    dest: "/etc/haproxy/haproxy.cfg"
    state: link

- name: "Перезапуск службы Haproxy 1.8"
  ansible.builtin.service:
    name: rh-haproxy18-haproxy
    state: restarted
  when: haproxy_config_result.changed