version: '3.8'
services:
  admin_helper:
    container_name: AH_api
    image: somekind/admin_helper_api:1.0.2
    networks:
      - backend

  admin_helper_web:
    container_name: AH_web
    image: somekind/admin_helper_web:1.0.2
    ports:
      - 80:80
    depends_on:
      - admin_helper
    networks:
      - backend

networks:
  backend:
    driver: bridge