- name: "Создание docker-compose файла"
  ansible.builtin.template:
    src: "docker-compose.j2"
    dest: "{{docker_data}}/docker-compose.yml"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "o=rw,g=r,a=r"

- name: "Создание конфига Haproxy"
  ansible.builtin.template:
    src: "haproxy.cfg.j2"
    dest: "{{docker_data}}/haproxy.cfg"
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "o=rw,g=r,a=r"