- name: "Установка Zabbix Agent 2"
  ansible.builtin.yum:
    name: https://repo.zabbix.com/zabbix/6.0/rhel/7/x86_64/zabbix-agent2-6.0.9-release1.el7.x86_64.rpm
    state: latest
    update_cache: no

- name: "Настройка конфига Zabbix Agent"
  lineinfile:
    path: "/etc/zabbix/zabbix_agent2.conf"
    regexp: "Server=127.0.0.1"
    line: "Server=0.0.0.0/0"

- name: "Перезапуск службы Zabbix Agent 2"
  ansible.builtin.service:
    name: zabbix-agent2
    enabled: yes
    state: restarted
